name: QA Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@8

      - name: Setup pnpm store
        run: pnpm store path

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Verify required docs
        run: |
          missing=false
          for f in docs/vision.md docs/product_backlog.md docs/design.md docs/execution_log.md docs/qa_plan.md docs/governance_traceability.md; do
            if [ ! -f "$f" ]; then
              echo "MISSING: $f"
              missing=true
            fi
          done
          if [ "$missing" = true ]; then
            echo "Required docs missing. See governance traceability."; exit 1
          fi
